### ISSUE TITLE
Nie responsywny href

### ISSUE THREAD

**Issue by MartynaSier** [KatarzynaOrzel/zad_rekrutacyjne#1]
https://github.com/KatarzynaOrzel/zad_rekrutacyjne/blob/7b49fdbe4258c9a3edb3551e38437c3d6eeb91c9/index.html#L31-L34;
// aby menu się "klikało" i przenosiło do podstron. zamiast href”#”, wpisać „href=index.html”/ „href=about.html” itd.

**Comment by kadlero** [comment]
Poprawione, dzięki że zwróciłaś na to uwagę.
