### ISSUE TITLE
logo hyperlink

### ISSUE THREAD

**Issue by MartynaSier** [KatarzynaOrzel/zad_rekrutacyjne#2]
https://github.com/KatarzynaOrzel/zad_rekrutacyjne/blob/7b49fdbe4258c9a3edb3551e38437c3d6eeb91c9/index.html#L27

Logo lewy górny róg nie działa, (rozwiązanie z href w issu dot linii 31-32, .) a po kliknięciu format logo zmienia się na przekreślenie, nie wiem czy to zabieg zamierzony 😊.

**Comment by kadlero** [comment]
Poprawione, winien styl hovera w 152 linijce pliku css.
Dzięki
