### ISSUE TITLE
Zoom-in / zoom-out mapy

### ISSUE THREAD

**Issue by MartynaSier** [KatarzynaOrzel/zad_rekrutacyjne#4]
https://github.com/KatarzynaOrzel/zad_rekrutacyjne/blob/596357fd5522d06e2ddffd16d7bb5792e52da768/contact.html#L76

możesz spróbować wymienić img mapy na faktyczną mapę, która pozwoli zrobić  zoom-in/ zoom-out.
Możesz to zrobić wykorzystując opcję „iframe” z podaniem jako src lokalizacji miejsca/adresu., fajnie opisane jest to np tutaj: Zoom-in/ zoom-out mapy (strona contact) można wprowadzić z wykorzystaniem opcji „iframe” z podaniem jako src lokalizacji miejsca/adresu.  :))

**Comment by kadlero** [comment]
Zrobione, dzięki.
